openapi: 3.0.3
info:
  version: 0.1.0
  title: Glassdoor API
  license:
    name: MIT
    url: https://github.com/noid-dev/codewars-openapi/blob/main/LICENSE
  description: |
    Official Glassdoor API documentation - [https://www.glassdoor.com/developer/](https://www.glassdoor.com/developer/index.htm)
servers:
  - url: https://api.glassdoor.com
security:
  - PartnerID: []
  - PartnerKey: []
paths:
  /api/api.htm:
    get:
      summary: Get user information.
      operationId: getUser
      description: Returns information about the user.
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/Action'
        - $ref: '#/components/parameters/Format'
        - $ref: '#/components/parameters/UserAgent'
        - $ref: '#/components/parameters/UserIP'
        - $ref: '#/components/parameters/Version'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  securitySchemes:
    PartnerID:
      type: apiKey
      in: query
      name: t.p
      description: Your partner id, as assigned by Glassdoor.
    PartnerKey:
      type: apiKey
      in: query
      name: t.k
      description: Your partner key, as assigned by Glassdoor.
  parameters:
    Action:
      name: action
      in: query
      required: true
      description: |
        The particular API call that you would like to make - see jobs, 
        reviews, salaries, etc. sub-sections for details.
      schema:
        type: string
        enum:
          - jobs
          - employers
          - salaries
    Format:
      name: format
      in: query
      required: true
      description: Either xml or json as you prefer.
      schema:
        type: string
        enum:
          - json
          - xml
    UserAgent:
      name: useragent
      in: query
      description: |
        The User-Agent (browser) of the end user to whom the API results will be shown. 
        Note that you can can obtain this from the "User-Agent" HTTP request header from the end-user.
      schema:
        type: string
        default: SwaggerUI/4.15.5
    UserIP:
      name: userip
      in: query
      description: The IP address of the end user to whom the API results will be shown.
      schema:
        type: string
        default: 0.0.0.0
    Version:
      name: v
      in: query
      required: true
      description: |
        The API version. 
        The current version is 1 except for jobs, which is currently version 1.1.
      schema:
        type: number
        enum:
          - 1
          - 1.1
  schemas:
    Response:
      type: object
      required:
        - success
        - status
      properties:
        success:
          type: boolean
          description: Operation outcome.
        status:
          type: string
          description: Response status.
        response:
          type: string
          description: Response JSON depending on the action.
  responses:
    Forbidden:
      description: |
        Access-Denied: your partner id/key are not correct, or not specified. Check the t.p and t.k params in your request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
