name: action
in: query
required: true
description: |
  The particular API call that you would like to make - see jobs, 
  reviews, salaries, etc. sub-sections for details.
schema:
  type: string
  enum:
    - jobs
    - employers
    - salaries