name: Build & Test

on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Bundle definitions
        run: npm run build >> $GITHUB_STEP_SUMMARY 2>&1

      - name: Validate definitions
        run: npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9
        with:
          name: gh-pages
          path: ./public/